# Generated by Django 4.2.3 on 2023-07-21 15:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('academic_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_name', models.CharField(max_length=100)),
                ('academic_status', models.BooleanField(default=True)),
                ('academic_created', models.DateTimeField(auto_now_add=True)),
                ('academic_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_status', models.BooleanField(default=True)),
                ('assignment_created', models.DateTimeField(auto_now_add=True)),
                ('assignment_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('course_status', models.BooleanField(default=True)),
                ('course_created', models.DateTimeField(auto_now_add=True)),
                ('course_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('department_status', models.BooleanField(default=True)),
                ('department_created', models.DateTimeField(auto_now_add=True)),
                ('department_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('enroll_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enroll_status', models.BooleanField(default=True)),
                ('enroll_created', models.DateTimeField(auto_now_add=True)),
                ('enroll_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(max_length=100)),
                ('faculty_status', models.BooleanField(default=True)),
                ('faculty_created', models.DateTimeField(auto_now_add=True)),
                ('faculty_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100)),
                ('group_status', models.BooleanField(default=True)),
                ('group_created', models.DateTimeField(auto_now_add=True)),
                ('group_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=50)),
                ('organization_status', models.BooleanField(default=True)),
                ('organization_created', models.DateTimeField(auto_now_add=True)),
                ('organization_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_year', models.CharField(max_length=4)),
                ('plan_status', models.BooleanField(default=True)),
                ('plan_created', models.DateTimeField(auto_now_add=True)),
                ('plan_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=100)),
                ('school_status', models.BooleanField(default=True)),
                ('school_created', models.DateTimeField(auto_now_add=True)),
                ('school_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semester_name', models.CharField(max_length=100)),
                ('semester_status', models.BooleanField(default=True)),
                ('semester_created', models.DateTimeField(auto_now_add=True)),
                ('semester_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_status', models.BooleanField(default=True)),
                ('student_created', models.DateTimeField(auto_now_add=True)),
                ('student_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=100)),
                ('teahcer_email', models.EmailField(max_length=254)),
                ('teacher_status', models.BooleanField(default=True)),
                ('teacher_created', models.DateTimeField(auto_now_add=True)),
                ('teacher_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_dni', models.IntegerField(unique=True)),
                ('user_password', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('user_last_name', models.CharField(max_length=100)),
                ('user_dob', models.DateField()),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='User_Type',
            fields=[
                ('user_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_type_name', models.CharField(max_length=100)),
                ('user_type_status', models.BooleanField(default=True)),
                ('user_type_created', models.DateTimeField(auto_now_add=True)),
                ('user_type_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='user_type',
            constraint=models.UniqueConstraint(fields=('user_type_name',), name='unique_user_type_name'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.user_type'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.organization'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.user'),
        ),
        migrations.AddField(
            model_name='student',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.organization'),
        ),
        migrations.AddField(
            model_name='student',
            name='school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.user'),
        ),
        migrations.AddField(
            model_name='semester',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.organization'),
        ),
        migrations.AddField(
            model_name='school',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.organization'),
        ),
        migrations.AddField(
            model_name='plan',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.organization'),
        ),
        migrations.AddField(
            model_name='group',
            name='assignment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.assignment'),
        ),
        migrations.AddField(
            model_name='group',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.organization'),
        ),
        migrations.AddField(
            model_name='group',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.teacher'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.organization'),
        ),
        migrations.AddField(
            model_name='enroll',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.group'),
        ),
        migrations.AddField(
            model_name='enroll',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.organization'),
        ),
        migrations.AddField(
            model_name='enroll',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.student'),
        ),
        migrations.AddField(
            model_name='department',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.organization'),
        ),
        migrations.AddField(
            model_name='course',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.organization'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='academic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.academic'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.organization'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.teacher'),
        ),
        migrations.AddField(
            model_name='academic',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.department'),
        ),
        migrations.AddField(
            model_name='academic',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.organization'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('user_dni',), name='unique_user_dni'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('user_email',), name='unique_user_email'),
        ),
    ]
